name: 'Inspect Docker Images'
description: 'Inspects Docker images and resolves their digests from any container registry'
author: 'Optivem'
branding:
  icon: 'search'
  color: 'blue'
inputs:
  image-urls:
    description: 'Image URLs to resolve digests for. Supports both newline-separated list or JSON array format'
    required: true
outputs:
  image-digest-urls:
    description: 'JSON array of digest URLs in the same order as input'
    value: ${{ steps.get-digests.outputs.digests }}
  image-inspect-data:
    description: 'JSON array of full Docker inspect data for each image in the same order as input'
    value: ${{ steps.get-digests.outputs.inspect-data }}
runs:
  using: 'composite'
  steps:
    - name: Resolve image digests
      id: get-digests
      shell: pwsh
      run: |
        & "${{ github.action_path }}/action.ps1" -ImageUrls '${{ inputs.image-urls }}'
