name: 'Resolve Latest Docker Digests'
description: 'Resolves Docker image digests from any container registry for multiple images'
author: 'Optivem'
branding:
  icon: 'search'
  color: 'blue'
inputs:
  image-urls:
    description: 'Image URLs to resolve digests for. Supports both newline-separated list or JSON array format'
    required: true
outputs:
  image-digest-urls:
    description: 'JSON array of digest URLs in the same order as input'
    value: ${{ steps.get-digests.outputs.digests }}
runs:
  using: 'composite'
  steps:
    - name: Resolve image digests
      id: get-digests
      shell: pwsh
      run: |
        & "${{ github.action_path }}/action.ps1" -ImageUrls '${{ inputs.image-urls }}'
