name: 'Inspect Docker Images'
description: 'Extracts Docker image digests from GitHub Container Registry for multiple images'
author: 'Optivem'
branding:
  icon: 'search'
  color: 'blue'
inputs:
  images:
    description: 'JSON array of images to inspect. Each image should have: repo-owner, repo-name, image-name, version'
    required: true
outputs:
  digests-json:
    description: 'JSON object containing all image digests'
    value: ${{ steps.get-digests.outputs.digests-json }}
runs:
  using: 'composite'
  steps:
    - name: Get image digests
      id: get-digests
      shell: pwsh
      run: |
        & "${{ github.action_path }}/action.ps1" -ImagesJson '${{ inputs.images }}'
