name: 'Resolve Latest Docker Digests'
description: 'Resolves the latest Docker image digests from GitHub Container Registry for multiple images'
author: 'Optivem'
branding:
  icon: 'search'
  color: 'blue'
inputs:
  images:
    description: 'JSON array of images to resolve. Each image should have: repoOwner, repoName, imageName (version is always "latest")'
    required: true
outputs:
  digests:
    description: 'JSON object containing all resolved image digests'
    value: ${{ steps.get-digests.outputs.digests }}
runs:
  using: 'composite'
  steps:
    - name: Resolve image digests
      id: get-digests
      shell: pwsh
      run: |
        & "${{ github.action_path }}/action.ps1" -ImagesJson '${{ inputs.images }}'
