name: 'Inspect Docker Image'
description: 'Extracts the Docker image digest from GitHub Container Registry'
author: 'Optivem'
branding:
  icon: 'search'
  color: 'blue'
inputs:
  repo-owner:
    description: 'GitHub repository owner (organization or user)'
    required: true
  repo-name:
    description: 'GitHub repository name'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  version:
    description: 'Docker image tag or version (e.g., v20241008-rc1)'
    required: true
outputs:
  digest:
    description: 'The exact digest of the latest Docker image'
    value: ${{ steps.get-digest.outputs.digest }}
runs:
  using: 'composite'
  steps:
    - name: Get latest image digest
      id: get-digest
      shell: pwsh
      run: |
        & "${{ github.action_path }}/action.ps1" -RepoOwner "${{ inputs.repo-owner }}" -RepoName "${{ inputs.repo-name }}" -ImageName "${{ inputs.image-name }}" -Version "${{ inputs.version }}"
